list_index:
    path:     /
    defaults: { _controller: "AppBundle:TaskList:index" }
    methods:  GET

list_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:TaskList:show" }
    methods:  GET

list_new:
    path:     /new
    defaults: { _controller: "AppBundle:TaskList:new" }
    methods:  [GET, POST]

list_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:TaskList:edit" }
    methods:  [GET, POST]

list_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:TaskList:delete" }
    methods:  DELETE
