app_index:
    path: /
    defaults:
        _controller: AppBundle:TaskList:index

app_list:
    resource: "@AppBundle/Resources/config/routing/tasklist.yml"
    prefix:   /list

app_task:
    resource: "@AppBundle/Resources/config/routing/task.yml"
    prefix:   /task
