services:
    app.factory.task_list:
        class: '%app.factory.class%'
        arguments:
            - '%app.entity.task_list.class%'

    app.repository.task_list:
        class: '%app.repository.class%'
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - '%app.entity.task_list.class%'

    app.factory.task:
        class: '%app.factory.class%'
        arguments:
            - '%app.entity.task.class%'

    app.repository.task:
        class: '%app.repository.class%'
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - '%app.entity.task.class%'

    app.form.type.task_list:
        class: '%app.form.type.task_list.class%'
        arguments:
            - '%app.entity.task_list.class%'
        tags:
            - { name: form.type }

    app.form.type.task:
        class: '%app.form.type.task.class%'
        arguments:
            - '%app.entity.task.class%'
            - '%app.entity.task_list.class%'
            - '@app.repository.task_list'
            - '@security.token_storage'
        tags:
            - { name: form.type }
