services:
    app.factory.task_list:
        class: '%app.factory.class%'
        arguments:
            - '%app.entity.task_list.class%'

    app.repository.task_list:
        class: '%app.repository.class%'
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - '%app.entity.task_list.class%'

    app.factory.task:
        class: '%app.factory.class%'
        arguments:
            - '%app.entity.task.class%'

    app.repository.task:
        class: '%app.repository.class%'
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - '%app.entity.task.class%'

    app.form.type.task_list:
        class: '%app.form.type.task_list.class%'
        arguments:
            - '%app.entity.task_list.class%'
        tags:
            - { name: form.type }

    app.form.type.task:
        class: '%app.form.type.task.class%'
        arguments:
            - '%app.entity.task.class%'
            - '%app.entity.task_list.class%'
            - '@app.repository.task_list'
            - '@security.token_storage'
        tags:
            - { name: form.type }

    app.form.extension.fos_user_profile:
        class: '%app.form.extension.fos_user_profile.class%'
        tags:
            - { name: form.type_extension, extended_type: FOS\UserBundle\Form\Type\ProfileFormType }

    app.voter.task_list:
        class: '%app.voter.task_list.class%'
        tags:
            - { name: security.voter }
        public: false

    app.voter.task:
        class: '%app.voter.task.class%'
        tags:
            - { name: security.voter }
        public: false

    app.listener.locale:
        class: '%app.listener.locale.class%'
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    app.listener.user_locale:
        class: '%app.listener.user_locale.class%'
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: kernel.event_listener, event: fos_user.profile.edit.success, method: onUserUpdate }
