AppBundle\Entity\TaskList:
    type: entity
    table: task_list
    repositoryClass: AppBundle\Repository\TaskListRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        created:
            type: datetime
    oneToMany:
        tasks:
            targetEntity: Task
            mappedBy: list
            orphanRemoval: true
    manyToOne:
        user:
            targetEntity: User
            inversedBy: lists
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
