AppBundle\Entity\Task:
    type: entity
    table: task
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        priority:
            type: integer
            length: 1
            nullable: true
        dueDate:
            type: datetime
            nullable: true
        created:
            type: datetime
        completed:
            type: datetime
            nullable: true
    manyToOne:
        list:
            targetEntity: TaskList
            inversedBy: tasks
            joinColumn:
                name: list_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
