AppBundle\Entity\TaskList:
    type: entity
    table: task_list
    repositoryClass: %app.repository.task_list.class%
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        created:
            type: datetime
    oneToMany:
        tasks:
            targetEntity: Task
            mappedBy: list
    lifecycleCallbacks: {  }
